name: ðŸ” Check PR Description Template

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr-body:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ” Validate PR template usage
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredSections = [
              '## ðŸ“Œ Summary',
              '## ðŸ› ï¸ Changes Introduced',
              '## ðŸ§ª How to Test',
              '## âœ… Acceptance Criteria Checklist'
            ];

            const prBody = context.payload.pull_request.body || '';
            const missing = requiredSections.filter(section => !prBody.includes(section));

            if (missing.length > 0) {
              const message = `
âš ï¸ **PR Template Check Failed**

Hi @${context.payload.pull_request.user.login}, your PR description is missing the following required section(s):

${missing.map(s => `- ${s}`).join('\n')}

Please update the description to follow the [PR Template](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/.github/pull_request_template.md) format.

Thank you! ðŸ™Œ
              `;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });

              core.setFailed("PR description is missing required sections.");
            } else {
              console.log("âœ… PR template validated successfully.");
            }
